In [2]:
!pip install kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.11/dist-packages (0.3.12)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from kagglehub) (4.67.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->kagglehub) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->kagglehub) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->kagglehub) (2025.4.26)

# Capstone Project Amazon Book Reviews

# Load Data from Kaggle

In [3]:
import re
import kagglehub
import pandas as pd

In [4]:


# Download latest version
path = kagglehub.dataset_download("mohamedbakhet/amazon-books-reviews")

file_name = '/Books_rating.csv'

ratings = pd.read_csv(path + file_name)

ratings.head()

,Id,Title,Price,User_id,profileName,review/helpfulness,review/score,review/time,review/summary,review/text
0,1882931173,Its Only Art If Its Well Hung!,NaN,AVCGYZL8FQQTD,"Jim of Oz ""jim-of-oz""",7/7,4.0,940636800,Nice collection of Julie Strain images,This is only for Julie Strain fans. It's a col...
1,0826414346,Dr. Seuss: American Icon,NaN,A30TK6U7DNS82R,Kevin Killian,10/10,5.0,1095724800,Really Enjoyed It,I don't care much for Dr. Seuss but after read...
2,0826414346,Dr. Seuss: American Icon,NaN,A3UH4UZ4RSVO82,John Granger,10/11,5.0,1078790400,Essential for every personal and Public Library,"If people become the books they read and if ""t..."
3,0826414346,Dr. Seuss: American Icon,NaN,A2MVUWT453QH61,"Roy E. Perry ""amateur philosopher""",7/7,4.0,1090713600,Phlip Nel gives silly Seuss a serious treatment,"Theodore Seuss Geisel (1904-1991), aka &quot;D..."
4,0826414346,Dr. Seuss: American Icon,NaN,A22X4XUPKF66MR,"D. H. Richards ""ninthwavestore""",3/3,4.0,1107993600,Good academic overview,Philip Nel - Dr. Seuss: American IconThis is b...

In [5]:
file_name = '/books_data.csv'

books = pd.read_csv(path + file_name)

books.head()

,Title,description,authors,image,previewLink,publisher,publishedDate,infoLink,categories,ratingsCount
0,Its Only Art If Its Well Hung!,NaN,['Julie Strain'],http://books.google.com/books/content?id=DykPA...,http://books.google.nl/books?id=DykPAAAACAAJ&d...,NaN,1996,http://books.google.nl/books?id=DykPAAAACAAJ&d...,['Comics & Graphic Novels'],NaN
1,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,A&C Black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,['Biography & Autobiography'],NaN
2,Wonderful Worship in Smaller Churches,This resource includes twelve principles in un...,['David R. Ray'],http://books.google.com/books/content?id=2tsDA...,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,NaN,2000,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,['Religion'],NaN
3,Whispers of the Wicked Saints,Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],http://books.google.com/books/content?id=aRSIg...,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,iUniverse,2005-02,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,['Fiction'],NaN
4,"Nation Dance: Religion, Identity and Cultural ...",NaN,['Edward Long'],NaN,http://books.google.nl/books?id=399SPgAACAAJ&d...,NaN,2003-03-01,http://books.google.nl/books?id=399SPgAACAAJ&d...,NaN,NaN

## Data Wrangling

In [6]:
ratings.describe()

               Price  review/score   review/time
count  481171.000000  3.000000e+06  3.000000e+06
mean       21.762656  4.215289e+00  1.132307e+09
std        26.206541  1.203054e+00  1.493202e+08
min         1.000000  1.000000e+00 -1.000000e+00
25%        10.780000  4.000000e+00  9.999072e+08
50%        14.930000  5.000000e+00  1.128298e+09
75%        23.950000  5.000000e+00  1.269130e+09
max       995.000000  5.000000e+00  1.362355e+09

In [7]:
ratings.shape

(3000000, 10)

In [8]:
books.shape

(212404, 10)

In [9]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 10 columns):
 #   Column              Dtype
---  ------              -----
 0   Id                  object
 1   Title               object
 2   Price               float64
 3   User_id             object
 4   profileName         object
 5   review/helpfulness  object
 6   review/score        float64
 7   review/time         int64
 8   review/summary      object
 9   review/text         object
dtypes: float64(2), int64(1), object(7)
memory usage: 228.9+ MB

In [10]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212404 entries, 0 to 212403
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Title          212403 non-null  object
 1   description    143962 non-null  object
 2   authors        180991 non-null  object
 3   image          160329 non-null  object
 4   previewLink    188568 non-null  object
 5   publisher      136518 non-null  object
 6   publishedDate  187099 non-null  object
 7   infoLink       188568 non-null  object
 8   categories     171205 non-null  object
 9   ratingsCount   49752 non-null   float64
dtypes: float64(1), object(9)
memory usage: 16.2+ MB

In [11]:
books.describe()

       ratingsCount
count  49752.000000
mean      21.252975
std      201.340431
min        1.000000
25%        1.000000
50%        2.000000
75%        5.000000
max     4895.000000

In [12]:
ratings_overview_rating = (
    ratings['review/score']
    .value_counts(normalize=True)   # fraction per rating
    * 100                           # → percentage
)

print("--" * 15)
print("Rating Overview (percent):\n", ratings_overview_rating)

------------------------------
Rating Overview (percent):
 review/score
5.0    60.244767
4.0    19.520533
3.0     8.476500
1.0     6.722933
2.0     5.035267
Name: proportion, dtype: float64

## Drop unneccesary Columns

In [13]:
books = books.drop(["image", "previewLink", "publisher", "infoLink"], axis=1)

In [14]:
ratings = ratings.drop(["profileName", "review/helpfulness", "review/summary"],axis=1)

In [15]:
books[books['Title']=='Its Only Art If Its Well Hung!']

,Title,description,authors,publishedDate,categories,ratingsCount
0,Its Only Art If Its Well Hung!,NaN,['Julie Strain'],1996,['Comics & Graphic Novels'],NaN

Check publishedDate data type

In [16]:
type(books['publishedDate'].iloc[0])

str

Check publishedDate Date format

In [17]:
books['publishedDate'].sample(10)

127618    1999-08-01
118505          1982
22479           1899
178765           NaN
99728     2013-08-27
129968    2005-10-01
79896           2002
190808    2022-01-04
67178     2008-03-02
36925     2001-12-14
Name: publishedDate, dtype: object

## Remove rows without publishedDate

In [18]:
books['publishedDate'].isna().sum()

np.int64(25305)

In [19]:
books_clean = books.dropna(subset=['publishedDate'])

In [20]:
books_clean.sample(10)

,Title,description,authors,publishedDate,categories,ratingsCount
136334,Elizabeth the queen: A play in three acts,"""In this drama we see Elizabeth and Essex, a r...",['Maxwell Anderson'],1934,['Authority'],NaN
45816,Lotto Trouble,A plan to steal a winning lottery ticket from ...,['Cash Kushel'],2003-03,['Fiction'],NaN
201209,THE TWILIGHT LANGUAGE; EXPLORATIONS IN BUDDHIS...,NaN,"['Roderick S. Bucknell', 'Martin Stuart-Fox']",1986-01-01,['Social Science'],NaN
168115,A Divine Cordial,NaN,"['Thomas Watson', 'Rev Terry Kulakowski, Editor']",2015-12-04,NaN,NaN
130555,Gen 13 Fantastic Four,NaN,"['Kevin Maguire', 'Karl C. Story', 'Richard St...",2001,"['Science fiction comic books, strips, etc']",NaN
202040,The Labrador Retriever: The Dog That Does It A...,President Clinton's Labrador Retriever is just...,"['Lisa Weiss', 'Emily Biegel']",1998-11-30,['Pets'],NaN
96367,Structural Steel Designer's Handbook,A Complete and Current Guide to Structural Ste...,"['Roger Brockenbrough', 'Frederick Merritt']",2011-02-07,['Technology & Engineering'],NaN
98113,Song Of Angels w/CD,"By award-winning author and lyricist, Gloria G...",['Gloria Gaither'],2010-10-05,['Juvenile Fiction'],1.0
210727,The Emperor's New Clothes (Creative Short Stor...,There was once an emperor who was only interes...,['Hans Christian Andersen'],2020-06-26,['Fiction'],NaN
39653,Deadly Medicine,She killed for thrills. The sensational story ...,"['Kelly Moore', 'Dan Reed']",1989,['Social Science'],NaN

In [21]:
books_clean = books_clean.copy()

## Convert Published Date to Date time object

In [22]:
def normalize_to_ymd(s):
    """
    Take a string s and return 'YYYY-MM-DD':
    - 'YYYY'        -> 'YYYY-01-01'
    - 'YYYY-M' or 'YYYY-MM' -> 'YYYY-MM-01'
    - 'YYYY-M-D', 'YYYY-MM-D', etc -> zero-pad and keep it
    - else: return as-is (to let to_datetime coerce it or fail to NaT)
    """
    if pd.isna(s):
        return None
    s = str(s).strip()
    # year only
    if re.fullmatch(r'\d{4}', s):
        return f'{s}-01-01'
    # year + month (1 or 2 digits)
    m = re.fullmatch(r'(\d{4})-(\d{1,2})$', s)
    if m:
        year, month = m.groups()
        return f'{year}-{month.zfill(2)}-01'
    # year-month-day (any digit count) → zero-pad each part
    parts = s.split('-')
    if len(parts) == 3 and all(p.isdigit() for p in parts):
        y, m, d = parts
        return f'{y.zfill(4)}-{m.zfill(2)}-{d.zfill(2)}'
    # otherwise leave it and let to_datetime errors='coerce'
    return s

In [23]:
# 1) normalize every string
books_clean['publishedDate_norm'] = books_clean['publishedDate'].apply(normalize_to_ymd)

In [24]:
# 2) parse to datetime64[ns], coercing any bad ones to NaT
books_clean['publishedDate_dt'] = pd.to_datetime(
    books_clean['publishedDate_norm'],
    format='%Y-%m-%d',
    errors='coerce'
)

In [25]:
books_clean.sample(10)

,Title,description,authors,publishedDate,categories,ratingsCount,publishedDate_norm,publishedDate_dt
42968,A Liar's Tale,In an incisive inquiry into the nature of dece...,['Jeremy Campbell'],2002,['Philosophy'],NaN,2002-01-01,2002-01-01
131005,Discretion,Despite being the Constitutional Head of State...,['Debtoru Chatterjee'],2016-07-15,NaN,NaN,2016-07-15,2016-07-15
175577,"Theology of culture,",Attempts to show the religious dimension in ma...,['Paul Tillich'],1959,['History'],1.0,1959-01-01,1959-01-01
67184,Red World of Polaris: The Adventures of Captai...,"""Red World of Polaris"" is one of the lost stor...",['Clark Ashton Smith'],2005-08,['Fiction'],NaN,2005-08-01,2005-08-01
147905,Sins of the Fathers: Based on the Oblivion (Th...,The Best New Horror has established itself as ...,['Stephen Jones'],2014-01-31,['Fiction'],2.0,2014-01-31,2014-01-31
89909,Pictures from an Expedition,Diane Smith's acclaimed novels feature strong ...,['Diane Smith'],2004-03-30,['Fiction'],3.0,2004-03-30,2004-03-30
182172,The Taste of New Wine,"Wherever it goes, The Taste of New Wine change...",['Keith Miller'],2009-12,['Family & Relationships'],NaN,2009-12-01,2009-12-01
51007,The blessed sun,NaN,['Bernadette Doyle'],2000,['Fathers and daughters'],NaN,2000-01-01,2000-01-01
50448,Free to be Slim,Emphasizes learning how to eat and how to live...,"['Neva Coyle', 'Marie Chapian']",1993,['Health & Fitness'],NaN,1993-01-01,1993-01-01
163396,Tap Dancing in Zen,"This sequel to ""Stumbling Toward Enlightenment...",['Geri Larkin'],2000,"['Body, Mind & Spirit']",NaN,2000-01-01,2000-01-01

In [26]:
books_clean.drop(columns=['publishedDate_norm','publishedDate'], inplace=True)

### Convert ratings review/time timestamp to date object

In [27]:
ratings['review_date'] = pd.to_datetime(ratings['review/time'], unit='s').dt.date

In [28]:
ratings.sample(10)

,Id,Title,Price,User_id,review/score,review/time,review/text,review_date
871854,1401092438,Love Me More: An Addict's Diary,NaN,A31OJ81N9QJDFA,5.0,1069372800,I received this book for my 51st birthday. I k...,2003-11-21
1549753,B000P1GVNE,"Augustus, A Novel",NaN,A32KLKCLVF55P2,4.0,1344902400,"I generally do not seek out ""epistolary"" books...",2012-08-14
2794150,B000EHIKXI,Cheaper By The Dozen,NaN,NaN,3.0,887673600,No growing pains have ever been more hilarious...,1998-02-17
1010437,0884195759,Thus Saith The Lord: How to know when God is s...,9.97,AU1H0UJR11AKN,4.0,1340582400,"As John Bevere states in this book, prophetic ...",2012-06-25
2892944,0745126006,One Pair of Hands,NaN,ALWKZ81HDSCC1,4.0,991785600,"Monica Dickens, the great-grandaughter of Char...",2001-06-06
1965023,B000O08FZ8,Jurassic Park,NaN,NaN,4.0,897609600,This book had a definate sense of intensity in...,1998-06-12
1811978,0839828500,"High, Wide and Lonesome: Growing Up on the Col...",NaN,A3BLUSTJ59WMUK,5.0,1357257600,I received this book in super timing. It only ...,2013-01-04
793186,1591132290,Buried in Burrywood,NaN,A36TCU1POQEJL9,5.0,1059091200,Be sure to get plenty of sleep before reading ...,2003-07-25
270433,B0000AACV3,The Myth of Laziness,NaN,NaN,5.0,1043452800,This book is just as relevant as Dr. Levine's ...,2003-01-25
1336909,B000NSFE6E,Families and Family Therapy,NaN,AOOT9EH3SJSYD,5.0,1333843200,Was happy to see that the product came exactly...,2012-04-08

### Drop rating's review/time

In [29]:
ratings.drop(columns=['review/time'], inplace=True)

##Rename columns in books

In [30]:
books_clean.rename(columns={'Title': 'book_title', 'authors': 'book_author', 'publishedDate_dt': 'published_date_dt',
                        'ratingsCount': 'ratings_count'}, inplace=True)

In [31]:
books_clean.columns

Index(['book_title', 'description', 'book_author', 'categories',
       'ratings_count', 'published_date_dt'],
      dtype='object')

## Rename Columns in ratings

In [32]:

ratings.rename(columns={'Id': 'book_id', 'Title': 'book_title', 'Price': 'book_price',
                          'User_id': 'user_id', 'review/text': 'review', 'review/score': 'rating'},
                              inplace=True)

In [33]:
ratings.columns

Index(['book_id', 'book_title', 'book_price', 'user_id', 'rating', 'review',
       'review_date'],
      dtype='object')

### Drop row with NA

In [34]:
books_clean.isnull().sum()

book_title                1
description           43553
book_author            7082
categories            16407
ratings_count        137502
published_date_dt       371
dtype: int64

In [35]:
books_clean.dropna(subset=['published_date_dt'], inplace=True)

In [36]:
books_clean.shape

(186728, 6)

In [37]:
ratings.shape

(3000000, 7)

In [38]:
ratings.isnull().sum()

book_id              0
book_title         208
book_price     2518829
user_id         561787
rating               0
review               8
review_date          0
dtype: int64

In [39]:
ratings.dropna(subset=['book_title'], inplace=True)

In [40]:
ratings.isnull().sum()

book_id              0
book_title           0
book_price     2518628
user_id         561774
rating               0
review               8
review_date          0
dtype: int64

## Feature Engineer Num of reviews in books

In [41]:
counts = (
    ratings
    .groupby('book_title')
    .size()
    .reset_index(name='num_of_review')
)

In [42]:
print(counts.shape)

(212403, 2)

In [43]:
books_clean = books_clean.merge(counts, on='book_title', how='inner')

In [44]:
books_clean.describe()

       ratings_count              published_date_dt  num_of_review
count   49570.000000                         186727  186727.000000
mean       21.313335  1995-12-03 13:08:52.210125056      14.144119
min         1.000000            1679-01-01 00:00:00       1.000000
25%         1.000000            1993-01-01 00:00:00       1.000000
50%         2.000000            2002-01-01 00:00:00       3.000000
75%         5.000000            2010-01-05 12:00:00       8.000000
max      4895.000000            2030-12-31 00:00:00   22023.000000
std       201.700654                            NaN     113.293356

In [45]:
mask = books_clean['num_of_review'].isna()
temp = books_clean[mask]
print(temp)

Empty DataFrame
Columns: [book_title, description, book_author, categories, ratings_count, published_date_dt, num_of_review]
Index: []

### Filter num of review >= 120 in books

In [46]:
books_clean[books_clean['num_of_review']>=120].shape[0]

2939

In [47]:
books_filtered = books_clean[books_clean['num_of_review']>=120].copy()

### Filter book from 2022 to end of data

In [48]:
# @title
book_filtered_2020_eoD = books_filtered[
    books_clean['published_date_dt'] >= pd.Timestamp('2021-01-01')
]

<ipython-input-48-18f1cb0506d0>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  book_filtered_2020_eoD = books_filtered[

In [49]:
# @title
book_filtered_2020_eoD.shape

(89, 7)

###Filter review based on the books records

In [72]:
ratings_filtered_2020_eoD = ratings[ratings['book_title'].isin(book_filtered_2020_eoD['book_title'])]

In [73]:
ratings_filtered_2020_eoD.shape

(32303, 7)

Sampling 2000 Observation

In [64]:
ratings_filtered_2020_eoD = ratings_filtered_2020_eoD.sample(n=2000,random_state=42).copy()

In [74]:
ratings_filtered_2020_eoD.isnull().sum()

book_id            0
book_title         0
book_price     29753
user_id         5694
rating             0
review             0
review_date        0
dtype: int64

In [75]:
ratings_filtered_2020_eoD.dropna(subset=['user_id'], inplace=True)

<ipython-input-75-41fd4adb60c5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ratings_filtered_2020_eoD.dropna(subset=['user_id'], inplace=True)

In [76]:
ratings_filtered_2020_eoD.shape

(26609, 7)

In [77]:
ratings_overview_rating = (
    ratings_filtered_2020_eoD['rating']
    .value_counts(normalize=True)   # fraction per rating
    * 100                           # → percentage
)

print("--" * 15)
print("Rating Overview (percent):\n", ratings_overview_rating)

------------------------------
Rating Overview (percent):
 rating
5.0    59.648991
4.0    20.906460
3.0     8.542223
1.0     6.276072
2.0     4.626254
Name: proportion, dtype: float64

### Feature Engineer Sentiment

In [78]:
ratings_filtered_2020_eoD['sentiment'] = ratings_filtered_2020_eoD['rating'].apply(lambda x: 0 if x < 3 else 1)

<ipython-input-78-435ed53092e6>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ratings_filtered_2020_eoD['sentiment'] = ratings_filtered_2020_eoD['rating'].apply(lambda x: 0 if x < 3 else 1)

In [79]:
book_filtered_2020_eoD.to_csv('/content/drive/MyDrive/Capstone_Project_IOD/book_filtered_2020_eoD.csv', index=True)

In [81]:
ratings_filtered_2020_eoD.to_csv('/content/drive/MyDrive/Capstone_Project_IOD/ratings_filtered_2020_eoD.csv', index=True)

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive